# Generated by Django 4.2.1 on 2024-09-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Комментарий'),
        ),
    ]
