# Generated by Django 4.2.1 on 2024-10-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_artiles_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
